### ISSUE TITLE
ADFSToolkit cannot import Manual Rules if they are written in "old style"

### ISSUE THREAD

**Issue by favvojohan** [canariecaf/adfstoolkit#104]
After adding SHA-support and AuthZ rules in the Get-ADFSTkManualSPSettings.ps1 the old style of getting attributes will make the toolkit carsh:
$TransformRules["eduPersonScopedAffiliation"] = $AllTransformRules["eduPersonScopedAffiliation"]
This is the new way of writing:
$TransformRules.eduPersonScopedAffiliation = $AllTransformRules.eduPersonScopedAffiliation

The reason is that SHA-support and AuthZ is calling Get-ADFSTkManualSPSettings.ps1 earlier than before and therefore $AllTransformRules is not loaded which makes the old style crash (even that transform rules are not looked for at that point).

**Comment by canariecaf** [comment]
Closing item as it's either resolved or in the backlog
