### ISSUE TITLE
enhance log viewing with specific log helper cmdlets

### ISSUE THREAD

**Issue by canariecaf** [canariecaf/adfstoolkit#11]
As we use eventlog for our activity, it may be helpful to have some specific cmdlets to assist viewing the log and possibly used to bundle output into a support request.

https://blogs.technet.microsoft.com/heyscriptingguy/2015/10/21/event-log-queries-using-powershell/

**Comment by teamktown** [comment]
some of this was done with improvements  to the event log id tags by Johan. Closing as some progress has been made
