### ISSUE TITLE
add appveyor tests for aggregate integrity checks

### ISSUE THREAD

**Issue by canariecaf** [canariecaf/adfstoolkit#12]
While appveyor can do CI tests, we need to tell it what to test. I propose these minimal ones:

[ ] validate a signed aggregate can be validated
[ ] validate an aggregate fails signature by bad hash value
[ ] validate an aggregate fails validation due to changes within the signed XML

This may require that we bundle sample tainted aggregates such that the tests are performed ok OR that we have the ability to fetch a signed aggregate and THEN attempt to manipulate THAT one (simply adding a character or changing a space should do) to trigger validation failure.

**Comment by teamktown** [comment]
nice to have but very hard to do and migrating to operational testing at federation level
