### ISSUE TITLE
bug: resolve problem with javascript error on button click where enter key works

### ISSUE THREAD

**Issue by teamktown** [canariecaf/adfstoolkit#144]
When using the REFEDS MFA enhancements, the javascript that is rendered in the default theme of ADFS has an error where the submission method needs to be improved to be companioned with the adapter

![image](https://user-images.githubusercontent.com/2530804/130641767-26f0a172-5977-4bcb-a307-2dc3ce0aea95.png)

compared with: 
![image](https://user-images.githubusercontent.com/2530804/130641833-9f005bb4-550b-41c1-aa1f-9dbf09d62a62.png)

The ADFSToolkit affirmed the approach to resolve is to adjust the adapter dll to improve the javascript being invoked

**Comment by favvojohan** [comment]
Solved by #145
