### ISSUE TITLE
enhance eduPersonAffiliation with additional assignment scenarios

### ISSUE THREAD

**Issue by canariecaf** [canariecaf/adfstoolkit#3]
This enhancement is for sites without an AD schema containing eduPersonAffiliation. 
For those we desire the attribute to be handled as follows and configurable in the config file

- [x] allow it to be populated directly from a schema attribute as specified in the config file (e.g. 'member')
- [x] allow it to be populated as a static setting from the configuration file if the schema attribute is not assigned
- [x] allow a mapping of affiliation values to any of the given values to be assigned from a group expression (e.g. student is when user is present in AD group 'isStudent')

it is worth noting that user may be present in multiple groups so we should strive for the calculation to encapsulate building a multivalued array for said members.

**Comment by favvojohan** [comment]
In my branch all of the above is possible, but we need to merge
