### ISSUE TITLE
Better error handling i Add-ADFSTk-SPRelyingPartyTrust.sp1

### ISSUE THREAD

**Issue by favvojohan** [canariecaf/adfstoolkit#45]
The following line of code in Add-ADFSTk-SPRelyingPartyTrust.sp1 should have better error handling (row 95):
$EntityCategories += $sp.Extensions.EntityAttributes.Attribute | ? Name -eq "http://macedir.org/entity-category" | select -ExpandProperty AttributeValue | % { ...

Í got the following error from Gothernburg University:
select : Property "AttributeValue" cannot be found.
At C:\Program Files\WindowsPowerShell\Modules\ADFSToolkit\0.9.1.40\Private\Add-ADFSTkSPRelyingPartyTrust.ps1:95 char:12
0
+ ... ir.org/entity-category" | select -ExpandProperty AttributeValue | % {
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Attribute:PSObject) [Select-Object], PSArgumentException
    + FullyQualifiedErrorId : ExpandPropertyNotFound,Microsoft.PowerShell.Commands.SelectObjectCommand

**Comment by teamktown** [comment]
@favvojohan and @teamktown reviewed and has not occured in v2 build -- closing and will re-open if it occurs.
