### ISSUE TITLE
To support signing code, migrate user specific SP overrides to inclusion in c:\ADFSToolkit

### ISSUE THREAD

**Issue by canariecaf** [canariecaf/adfstoolkit#49]
When Powershell code is signed, any of the powershell code to be included requires a code signing block. This means that anything to override and SP setting will break the signature in the current model.

To support an execution policy of remoteSigned externalizing the SP overrides into user controlled space/origin is required.
A known style used by Apache, NGinx, and freeRADIUS will be used. The style is a directory of sites-available (things you can use), and sites-enabled (things actively configured).
Adopting this model allows for flexibility of selecting known configuration for Service Providers/Relying Parties and ingesting all records in sites-enabled will permit easier, more fine grained updates and NOT require a Module reload.

A parent directory set to the version of the Module will be used to do better mitigating Module updates triggering errors in running code. 

Functional features required:
- [ ] Break out examples in config/get-ADFSTkManualSPSettings.ps1 into a subdirectory in the module 'default'/site-examples using a file-safe naming-convention that ends with .ps1.txt
- [ ] when new-ADFSTkConfiguration is executed, do the following:
- [ ] force the creation of the following directory structure within C:\ADFSToolkit if it does not already exist:
- the latest version number (<vnum>) and nested within these folders
- config
- cache
- sites-available
- sites-enabled
- sites-disabled
- sites-examples
- [ ] copy all *ps1.txt files in <module>/config/default/site-examples into c:\ADFSToolkit\site-examples
-[ ] update **New-ADFSTkConfiguration.ps1** around line 245 to add the enumeration of all ps1 files to be inserted into the array of SP overrides (in the spirit of ingesting the filter of any subfiles tagged *.ps1 in a targeted subdirectory (candidate to be a public Function get-ADFSTUserSPOverrides.ps1.

The act of enabling a service is placing to place a file in sites-available and issue:

**publish-ADFSTkSPSettings** -name <filename> -config /path/config.xml [-refresh] which will:
- attempt to load the given config and named powershell anchored in sites-available 
- copy the file into c:\adfstoolkit\<module-version>\sites-enabled
- if -refresh is provided it will trigger the issuance of the command import-ADFSTkMetadata for the invocation of the import of that record.
- a log record will be written to the ADFSTk EventLog

- [ ] **unpublish-ADFSTkSPSettings** -name <filename -config /path/config.xml -refresh will:
- attempt to load the given config and named powershell anchored in sites-available 
- ask the user 'are you sure' and default to No of file moving from sites-enabled to sites-disabled
- move the file
- if -refresh is provided it will trigger the issuance of the command import-ADFSTkMetadata for the invocation of the import of that record.
- a log record will be written to the ADFSTk EventLog

In the above commands, the notion of which aggregate the entity originates from is important and pivots on the notion of the configuration file to source the aggregate fingerprint.  It is plausible that an entityid MAY exist in both but one or the other is tweaked and may need to be reviewed during implementation.

**Comment by canariecaf** [comment]
after peer review, the original model propose was not adopted. 
This proposed model is being tested:
- [ ] adopt a model of c:\ADFSToolkit\<version>\ as the install root for user-space
- [ ] migrate config and cache to said user-space, version dependant
- [ ] drop in blank template override in said user-space

**Comment by favvojohan** [comment]
Why should we have the version as a part of the path? I think that will make upgrades more difficult. The ADFSTk never writes to the folder so it should be safe.

**Comment by canariecaf** [comment]
I agree however the challenge is that if we want a robust lifecycle pathway, we need to drop versions in and then migrate from old to new. 
Abstracting out the code in the module is good and works well for signature and purposes of 'things don't change there' however when update-module is run a 2nd,3rd, or Nth time, it leaves each previous version in place in the powershell module folder.

As we migrate from one version to another, it's much easier to leave things in place and permits a fallback/rollback procedure to simply point to the previous version as the required version with no changes.

This also permits us to inspect the previous version configuration and migrate/adjust things post update-module so that we can pull installations forward with fewer errors. 

This step is to allow us to enhace the get-ADFSTkConfiguration -migrateversion where we can interrogate which versions are on the host and may be able to rewrite/inject things into the config as necessary.

**Comment by favvojohan** [comment]
Ok good point. If we make changes to the configuration schema it's nice to have them separated. But in that case I think it's better to have one ADFSTk folder and version folders under it,  C:\ADFSToolkit\[version]. It's more like the modules folder and it doesn't pollute the C: as much :)
