### ISSUE TITLE
Verify configuration on startup

### ISSUE THREAD

**Issue by favvojohan** [canariecaf/adfstoolkit#8]
The configuration should be verified on startup.

Different configurations for different versions.

**Comment by favvojohan** [comment]
I made a xsd for the current configuration and validates the config against that on startup.

Next step is to be version-aware - if we need that - the xsd for the installed version should always be correct... But let's talk about that.

Another possibility is to have xsd’s for all versions in the code so the latest Verify-Configuration cmdlet can verify all different configuration versions.

**Comment by canariecaf** [comment]
While the work on this is completed (to parse things with the XSD), this will be considered for the .next iteration as opposed to the RC1.

**Comment by favvojohan** [comment]
A control is made that the configuration is a valid version at startup with v2.0.0

**Comment by teamktown** [comment]
Some validation is in v2 release -- closing
